training:
  stop:
    iterations: 700
  ray:
    num_env_runners: 0
    num_envs_per_env_runner: 1
    num_learners: 0
    num_gpus_per_learner: 0
  ppo:
    gamma: 0.99
    lambda_: 0.95
    lr: 0.0001
    clip_param: 0.1
    grad_clip: 0.5
    entropy_coeff: 0.0005
    vf_loss_coeff: 1.0
    train_batch_size_per_learner: 4096
    minibatch_size: 512
    num_epochs: 5
    rollout_fragment_length: auto
  checkpoint:
    directory: checkpoints/ppo
    frequency_iters: 50
  evaluation:
    enabled: true
    episodes: 10
    frequency_iters: 50
    report_path: reports/
    render: true
    gif_path: gifs/
    render_stride: 4
